### ISSUE TITLE
Failing tests  

### ISSUE THREAD

**Issue by wilke** [ExaWorks/psij-python#306]
After updating the repo:

psij-python]$ ./psij-ci-run
```
From https://github.com/ExaWorks/psij-python
 * branch            HEAD       -> FETCH_HEAD
Reading configuration... OK
error: Unknown subcommand: get-url
usage: git remote [-v | --verbose]
   or: git remote add [-t <branch>] [-m <master>] [-f] [--tags|--no-tags] [--mirror=<fetch|push>] <name> <url>
   or: git remote rename <old> <new>
   or: git remote remove <name>
   or: git remote set-head <name> (-a | -d | <branch>)
   or: git remote [-v | --verbose] show [-n] <name>
   or: git remote prune [-n | --dry-run] <name>
   or: git remote [-v | --verbose] update [-p | --prune] [(<group> | <remote>)...]
   or: git remote set-branches [--add] <name> <branch>...
   or: git remote set-url [--push] <name> <newurl> [<oldurl>]
   or: git remote set-url --add <name> <newurl>
   or: git remote set-url --delete <name> <url>

    -v, --verbose         be verbose; must be placed before a subcommand


Traceback (most recent call last):
  File "tests/ci_runner.py", line 243, in <module>
    update_origin()
  File "tests/ci_runner.py", line 199, in update_origin
    old_url = run('git', 'remote', 'get-url', 'origin')
  File "tests/ci_runner.py", line 58, in run
    raise subprocess.CalledProcessError(p.returncode, args, output=p.stdout)
subprocess.CalledProcessError: Command '('git', 'remote', 'get-url', 'origin')' returned non-zero exit status 129.
```

**Comment by hategan** [comment]
What are the OS and git version?

**Comment by wilke** [comment]
Tested and fixed, thanks.
