### ISSUE TITLE
Failing test on theta

### ISSUE THREAD

**Issue by wilke** [ExaWorks/psij-python#308]
Path/Permission problem and gitlab reports this as success rather than failure.

From https://github.com/ExaWorks/psi-j-python
[287](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L287) * branch            HEAD       -> FETCH_HEAD
[288](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L288)Reading configuration... OK
[289](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L289)Patching testing.conf... OK
[290](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L290)Patching psij-ci-run... OK
[291](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L291)Updating git url to https://gitlab-ci-token@gitlab-ci.tmi.alcf.anl.gov/anl/csc249adtr01/psij-python.git... OK
[292](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L292)Cloning repository... OK
[293](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L293)Testing branch "main"... INTERNALERROR> Traceback (most recent call last):
[294](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L294)INTERNALERROR>   File "/opt/python/3.9.4.1/lib/python3.9/pathlib.py", line 1312, in mkdir
[295](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L295)INTERNALERROR>     self._accessor.mkdir(self, mode)
[296](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L296)INTERNALERROR> FileNotFoundError: [Errno 2] No such file or directory: '/home/csc249adtr01/.psij'
[297](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L297)INTERNALERROR> 
[298](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L298)INTERNALERROR> During handling of the above exception, another exception occurred:
[299](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L299)INTERNALERROR> 
[300](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L300)INTERNALERROR> Traceback (most recent call last):
[301](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L301)INTERNALERROR>   File "/lus/theta-fs0/projects/ci/ecp/working/thetalogin3/shell-01/csc249adtr01/builds/aZ9WMnrn/000/anl/csc249adtr01/psij-python/.packages/_pytest/main.py", line 264, in wrap_session
[302](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L302)INTERNALERROR>     config._do_configure()
[303](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L303)INTERNALERROR>   File "/lus/theta-fs0/projects/ci/ecp/working/thetalogin3/shell-01/csc249adtr01/builds/aZ9WMnrn/000/anl/csc249adtr01/psij-python/.packages/_pytest/config/__init__.py", line 996, in _do_configure
[304](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L304)INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
[305](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L305)INTERNALERROR>   File "/lus/theta-fs0/projects/ci/ecp/working/thetalogin3/shell-01/csc249adtr01/builds/aZ9WMnrn/000/anl/csc249adtr01/psij-python/.packages/pluggy/_hooks.py", line 277, in call_historic
[306](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L306)INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
[307](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L307)INTERNALERROR>   File "/lus/theta-fs0/projects/ci/ecp/working/thetalogin3/shell-01/csc249adtr01/builds/aZ9WMnrn/000/anl/csc249adtr01/psij-python/.packages/pluggy/_manager.py", line 80, in _hookexec
[308](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L308)INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
[309](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L309)INTERNALERROR>   File "/lus/theta-fs0/projects/ci/ecp/working/thetalogin3/shell-01/csc249adtr01/builds/aZ9WMnrn/000/anl/csc249adtr01/psij-python/.packages/pluggy/_callers.py", line 60, in _multicall
[310](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L310)INTERNALERROR>     return outcome.get_result()
[311](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L311)INTERNALERROR>   File "/lus/theta-fs0/projects/ci/ecp/working/thetalogin3/shell-01/csc249adtr01/builds/aZ9WMnrn/000/anl/csc249adtr01/psij-python/.packages/pluggy/_result.py", line 60, in get_result
[312](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L312)INTERNALERROR>     raise ex[1].with_traceback(ex[2])
[313](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L313)INTERNALERROR>   File "/lus/theta-fs0/projects/ci/ecp/working/thetalogin3/shell-01/csc249adtr01/builds/aZ9WMnrn/000/anl/csc249adtr01/psij-python/.packages/pluggy/_callers.py", line 39, in _multicall
[314](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L314)INTERNALERROR>     res = hook_impl.function(*args)
[315](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L315)INTERNALERROR>   File "/tmp/tmptkn37x3v/code/tests/conftest.py", line 187, in pytest_configure
[316](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L316)INTERNALERROR>     (env, key), log = _capture_log(partial(_discover_environment, config))
[317](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L317)INTERNALERROR>   File "/tmp/tmptkn37x3v/code/tests/conftest.py", line 167, in _capture_log
[318](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L318)INTERNALERROR>     result = fn()
[319](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L319)INTERNALERROR>   File "/tmp/tmptkn37x3v/code/tests/conftest.py", line 360, in _discover_environment
[320](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L320)INTERNALERROR>     SETTINGS_DIR.mkdir(parents=True, exist_ok=True)
[321](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L321)INTERNALERROR>   File "/opt/python/3.9.4.1/lib/python3.9/pathlib.py", line 1316, in mkdir
[322](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L322)INTERNALERROR>     self.parent.mkdir(parents=True, exist_ok=True)
[323](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L323)INTERNALERROR>   File "/opt/python/3.9.4.1/lib/python3.9/pathlib.py", line 1312, in mkdir
[324](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L324)INTERNALERROR>     self._accessor.mkdir(self, mode)
[325](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L325)INTERNALERROR> PermissionError: [Errno 13] Permission denied: '/home/csc249adtr01'
[326](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L326)OK

[327](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L327)
Cleaning up project directory and file based variables
00:00

[328](https://gitlab-ci.alcf.anl.gov/anl/csc249adtr01/psij-python/-/jobs/73289#L328) Job succeeded

**Comment by hategan** [comment]
Well, it is a success in that the test suite ran, but individual tests might have failed.

I'm not sure I can help much with the permission denied problem without a theta account. It looks like a random user is created for the job, but the home directory for that user is not created, but maybe you want to confirm some of the details using some carefully designed debugging jobs.

**Comment by wilke** [comment]
Test suite running and reporting to dashboard
