### ISSUE TITLE
SLURM launcher log configuration

### ISSUE THREAD

**Issue by j-woz** [ExaWorks/psij-python#356]
I am trying to turn on launcher_log_file and get:

```
cfg = psij.JobExecutorConfig(launcher_log_file=args.TURBINE_OUTPUT / "launcher.log")
jex = psij.JobExecutor.get_instance(args.executor, config=cfg)
...
jex.submit(job)

Exception in thread slurm Queue Polling Thread:
Traceback (most recent call last):
  File "/home/woz/W/Public/sfw/Miniconda-psij/lib/python3.9/threading.py", line 980, in _bootstrap_inner
<psij.job_spec.JobSpec object at 0x2ae706eef700>
    self.run()
  File "/home/woz/W/Public/sfw/Miniconda-psij/lib/python3.9/site-packages/psij/executors/batch/batch_scheduler_executor.py", line 573, in run
    time.sleep(self.config.initial_queue_polling_delay)
AttributeError: 'JobExecutorConfig' object has no attribute 'initial_queue_polling_delay'

```

**Comment by hategan** [comment]
Use an instance of `BatchSchedulerExecutorConfig` rather than `JobExecutorConfig`.

Also, related, #357.

**Comment by j-woz** [comment]
That worked, thanks.
